---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-dnf-data-storage
  namespace: dnf-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-dnf-log-storage
  namespace: dnf-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client


# Replace 'worker-node01' with any one of your cluster worker nodes hostname.
# kubectl get nodes