apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnf-server-new
  namespace: dnf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnf-server-new
  template:
    metadata:
      labels:
        app: dnf-server-new
    spec:
      containers:
        - name: dnf-server-new
          image: llnut/dnf:debian13-server-qf1031-latest
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "2"
          ports:
            - containerPort: 5505
              protocol: TCP
            - containerPort: 7001
              protocol: TCP
            - containerPort: 7200
              protocol: TCP
            - containerPort: 10011
              protocol: TCP
            - containerPort: 10052
              protocol: TCP

            - containerPort: 7001
              protocol: UDP
            - containerPort: 7200
              protocol: UDP
            - containerPort: 11011
              protocol: UDP
            - containerPort: 11052
              protocol: UDP
            - containerPort: 2311
              protocol: UDP
            - containerPort: 2312
              protocol: UDP
            - containerPort: 2313
              protocol: UDP
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MYSQL_HOST
              value: "dnf-mysql-server-new.dnf-server"
            - name: MYSQL_PORT
              value: "4000"
            - name: MYSQL_GAME_ALLOW_IP
              value: "%"
            - name: DNF_DB_ROOT_PASSWORD
              value: "88888888"
            - name: GATE_AES_KEY
              value: "a1b2c3d4e5f6789012345678901234567890abcdef0123456789abcdef012345"
            - name: PUBLIC_IP
              value: "172.31.0.11"
            # - name: TUNE_PROFILE
            #   value: "small"
            # - name: TUNE_VERBOSE
            #   value: "true"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: dnf-server-log
              mountPath: /home/neople/game/log
            - name: dnf-server-data
              mountPath: /data
            - name: memory
              mountPath: /dev/shm
      volumes:
        - name: dnf-server-log
          persistentVolumeClaim:
            claimName: new-dnf-log-storage
        - name: dnf-server-data
          persistentVolumeClaim:
            claimName: new-dnf-data-storage
        - name: memory
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
